"""
Статический маппинг городов на часовые пояса
Используется как fallback когда Nominatim недоступен
"""

# Маппинг городов на часовые пояса
CITY_TIMEZONE_MAP = {
    # Россия
    'москва': 'Europe/Moscow',
    'moscow': 'Europe/Moscow',
    'санкт-петербург': 'Europe/Moscow',
    'санкт петербург': 'Europe/Moscow',
    'saint petersburg': 'Europe/Moscow',
    'st petersburg': 'Europe/Moscow',
    'екатеринбург': 'Asia/Yekaterinburg',
    'yekaterinburg': 'Asia/Yekaterinburg',
    'новосибирск': 'Asia/Novosibirsk',
    'novosibirsk': 'Asia/Novosibirsk',
    'владивосток': 'Asia/Vladivostok',
    'vladivostok': 'Asia/Vladivostok',
    'казань': 'Europe/Moscow',
    'kazan': 'Europe/Moscow',
    'нижний новгород': 'Europe/Moscow',
    'nizhny novgorod': 'Europe/Moscow',
    'челябинск': 'Asia/Yekaterinburg',
    'chelyabinsk': 'Asia/Yekaterinburg',
    'омск': 'Asia/Omsk',
    'omsk': 'Asia/Omsk',
    'самара': 'Europe/Samara',
    'samara': 'Europe/Samara',
    'ростов-на-дону': 'Europe/Moscow',
    'rostov-na-donu': 'Europe/Moscow',
    'ростов на дону': 'Europe/Moscow',
    'уфа': 'Asia/Yekaterinburg',
    'ufa': 'Asia/Yekaterinburg',
    'красноярск': 'Asia/Krasnoyarsk',
    'krasnoyarsk': 'Asia/Krasnoyarsk',
    'воронеж': 'Europe/Moscow',
    'voronezh': 'Europe/Moscow',
    'пермь': 'Asia/Yekaterinburg',
    'perm': 'Asia/Yekaterinburg',
    'волгоград': 'Europe/Volgograd',
    'volgograd': 'Europe/Volgograd',
    'краснодар': 'Europe/Moscow',
    'krasnodar': 'Europe/Moscow',
    'саратов': 'Europe/Saratov',
    'saratov': 'Europe/Saratov',
    'тюмень': 'Asia/Yekaterinburg',
    'tyumen': 'Asia/Yekaterinburg',
    'тольятти': 'Europe/Samara',
    'tolyatti': 'Europe/Samara',
    'ижевск': 'Europe/Samara',
    'izhevsk': 'Europe/Samara',
    'сочи': 'Europe/Moscow',
    'sochi': 'Europe/Moscow',
    'адлер': 'Europe/Moscow',
    'adler': 'Europe/Moscow',
    'геленджик': 'Europe/Moscow',
    'gelendzhik': 'Europe/Moscow',
    'новороссийск': 'Europe/Moscow',
    'novorossiysk': 'Europe/Moscow',
    'подольск': 'Europe/Moscow',
    'podolsk': 'Europe/Moscow',

    # США
    'new york': 'America/New_York',
    'нью-йорк': 'America/New_York',
    'нью йорк': 'America/New_York',
    'los angeles': 'America/Los_Angeles',
    'лос-анджелес': 'America/Los_Angeles',
    'лос анджелес': 'America/Los_Angeles',
    'chicago': 'America/Chicago',
    'чикаго': 'America/Chicago',
    'houston': 'America/Chicago',
    'хьюстон': 'America/Chicago',
    'phoenix': 'America/Phoenix',
    'феникс': 'America/Phoenix',
    'philadelphia': 'America/New_York',
    'филадельфия': 'America/New_York',
    'san antonio': 'America/Chicago',
    'сан-антонио': 'America/Chicago',
    'san diego': 'America/Los_Angeles',
    'сан-диего': 'America/Los_Angeles',
    'dallas': 'America/Chicago',
    'даллас': 'America/Chicago',
    'san jose': 'America/Los_Angeles',
    'сан-хосе': 'America/Los_Angeles',
    'austin': 'America/Chicago',
    'остин': 'America/Chicago',
    'jacksonville': 'America/New_York',
    'джексонвилл': 'America/New_York',
    'miami': 'America/New_York',
    'майами': 'America/New_York',
    'seattle': 'America/Los_Angeles',
    'сиэтл': 'America/Los_Angeles',
    'denver': 'America/Denver',
    'денвер': 'America/Denver',
    'washington': 'America/New_York',
    'вашингтон': 'America/New_York',
    'boston': 'America/New_York',
    'бостон': 'America/New_York',
    'las vegas': 'America/Los_Angeles',
    'лас-вегас': 'America/Los_Angeles',

    # Европа
    'london': 'Europe/London',
    'лондон': 'Europe/London',
    'paris': 'Europe/Paris',
    'париж': 'Europe/Paris',
    'berlin': 'Europe/Berlin',
    'берлин': 'Europe/Berlin',
    'madrid': 'Europe/Madrid',
    'мадрид': 'Europe/Madrid',
    'rome': 'Europe/Rome',
    'рим': 'Europe/Rome',
    'warsaw': 'Europe/Warsaw',
    'варшава': 'Europe/Warsaw',
    'vienna': 'Europe/Vienna',
    'вена': 'Europe/Vienna',
    'prague': 'Europe/Prague',
    'прага': 'Europe/Prague',
    'budapest': 'Europe/Budapest',
    'будапешт': 'Europe/Budapest',
    'stockholm': 'Europe/Stockholm',
    'стокгольм': 'Europe/Stockholm',
    'copenhagen': 'Europe/Copenhagen',
    'копенгаген': 'Europe/Copenhagen',
    'oslo': 'Europe/Oslo',
    'осло': 'Europe/Oslo',
    'helsinki': 'Europe/Helsinki',
    'хельсинки': 'Europe/Helsinki',
    'amsterdam': 'Europe/Amsterdam',
    'амстердам': 'Europe/Amsterdam',
    'brussels': 'Europe/Brussels',
    'брюссель': 'Europe/Brussels',
    'lisbon': 'Europe/Lisbon',
    'лиссабон': 'Europe/Lisbon',
    'athens': 'Europe/Athens',
    'афины': 'Europe/Athens',
    'bucharest': 'Europe/Bucharest',
    'бухарест': 'Europe/Bucharest',
    'istanbul': 'Europe/Istanbul',
    'стамбул': 'Europe/Istanbul',
    'barcelona': 'Europe/Madrid',
    'барселона': 'Europe/Madrid',
    'bilbao': 'Europe/Madrid',
    'бильбао': 'Europe/Madrid',

    # Турция
    'анталья': 'Europe/Istanbul',
    'antalya': 'Europe/Istanbul',
    'белек': 'Europe/Istanbul',
    'belek': 'Europe/Istanbul',
    'кемер': 'Europe/Istanbul',
    'kemer': 'Europe/Istanbul',
    'сиде': 'Europe/Istanbul',
    'side': 'Europe/Istanbul',
    'аланья': 'Europe/Istanbul',
    'alanya': 'Europe/Istanbul',

    # Прибалтика
    'таллин': 'Europe/Tallinn',
    'tallinn': 'Europe/Tallinn',
    'эстония': 'Europe/Tallinn',
    'estonia': 'Europe/Tallinn',
    'рига': 'Europe/Riga',
    'riga': 'Europe/Riga',
    'вильнюс': 'Europe/Vilnius',
    'vilnius': 'Europe/Vilnius',

    # Азия
    'tokyo': 'Asia/Tokyo',
    'токио': 'Asia/Tokyo',
    'beijing': 'Asia/Shanghai',
    'пекин': 'Asia/Shanghai',
    'shanghai': 'Asia/Shanghai',
    'шанхай': 'Asia/Shanghai',
    'hong kong': 'Asia/Hong_Kong',
    'гонконг': 'Asia/Hong_Kong',
    'singapore': 'Asia/Singapore',
    'сингапур': 'Asia/Singapore',
    'seoul': 'Asia/Seoul',
    'сеул': 'Asia/Seoul',
    'bangkok': 'Asia/Bangkok',
    'бангкок': 'Asia/Bangkok',
    'dubai': 'Asia/Dubai',
    'дубай': 'Asia/Dubai',
    'delhi': 'Asia/Kolkata',
    'дели': 'Asia/Kolkata',
    'mumbai': 'Asia/Kolkata',
    'мумбаи': 'Asia/Kolkata',
    'alwar': 'Asia/Kolkata',

    # Индонезия
    'pamekasan': 'Asia/Jakarta',
    'jakarta': 'Asia/Jakarta',
    'джакарта': 'Asia/Jakarta',

    # Австралия
    'sydney': 'Australia/Sydney',
    'сидней': 'Australia/Sydney',
    'melbourne': 'Australia/Melbourne',
    'мельбурн': 'Australia/Melbourne',
    'brisbane': 'Australia/Brisbane',
    'брисбен': 'Australia/Brisbane',

    # Африка
    'cairo': 'Africa/Cairo',
    'каир': 'Africa/Cairo',
    'johannesburg': 'Africa/Johannesburg',
    'йоханнесбург': 'Africa/Johannesburg',

    # Южная Америка
    'sao paulo': 'America/Sao_Paulo',
    'сан-паулу': 'America/Sao_Paulo',
    'rio de janeiro': 'America/Sao_Paulo',
    'рио-де-жанейро': 'America/Sao_Paulo',
    'buenos aires': 'America/Argentina/Buenos_Aires',
    'буэнос-айрес': 'America/Argentina/Buenos_Aires',
}


def get_timezone_from_mapping(city_name: str) -> str:
    """
    Получает часовой пояс из статического маппинга

    Args:
        city_name: Название города

    Returns:
        Название часового пояса или None
    """
    city_lower = city_name.lower().strip()
    return CITY_TIMEZONE_MAP.get(city_lower)
